#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${AIRFLOW_DB_USER}') THEN
        CREATE ROLE ${AIRFLOW_DB_USER} LOGIN PASSWORD '${AIRFLOW_DB_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${PLATFORM_ADMIN_USER}') THEN
        CREATE ROLE ${PLATFORM_ADMIN_USER} LOGIN PASSWORD '${PLATFORM_ADMIN_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${EDU_WRITER_USER}') THEN
        CREATE ROLE ${EDU_WRITER_USER} LOGIN PASSWORD '${EDU_WRITER_PASSWORD}';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'student_readonly') THEN
        CREATE ROLE student_readonly NOLOGIN;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'student_sandbox_owner') THEN
        CREATE ROLE student_sandbox_owner NOLOGIN;
    END IF;

END
\$\$;
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
ALTER ROLE ${AIRFLOW_DB_USER} WITH LOGIN PASSWORD '${AIRFLOW_DB_PASSWORD}';
ALTER ROLE ${PLATFORM_ADMIN_USER} WITH LOGIN CREATEROLE CREATEDB INHERIT PASSWORD '${PLATFORM_ADMIN_PASSWORD}';
ALTER ROLE ${EDU_WRITER_USER} WITH LOGIN PASSWORD '${EDU_WRITER_PASSWORD}';
GRANT student_readonly TO ${PLATFORM_ADMIN_USER} WITH ADMIN OPTION;
GRANT student_sandbox_owner TO ${PLATFORM_ADMIN_USER} WITH ADMIN OPTION;
SQL

db_exists="$(psql -tAc "SELECT 1 FROM pg_database WHERE datname = '${EDU_PLATFORM_DB}'" --username "$POSTGRES_USER" --dbname "$POSTGRES_DB")"
if [[ "$db_exists" != "1" ]]; then
  psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" \
    -c "CREATE DATABASE ${EDU_PLATFORM_DB} OWNER ${PLATFORM_ADMIN_USER};"
fi

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
ALTER DATABASE ${POSTGRES_DB} OWNER TO ${AIRFLOW_DB_USER};
GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB} TO ${AIRFLOW_DB_USER};
GRANT ALL ON SCHEMA public TO ${AIRFLOW_DB_USER};
ALTER SCHEMA public OWNER TO ${AIRFLOW_DB_USER};
SQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$EDU_PLATFORM_DB" <<SQL
CREATE SCHEMA IF NOT EXISTS raw AUTHORIZATION ${EDU_WRITER_USER};

GRANT CONNECT ON DATABASE ${EDU_PLATFORM_DB} TO ${EDU_WRITER_USER};
GRANT CONNECT ON DATABASE ${EDU_PLATFORM_DB} TO student_readonly;
GRANT CREATE ON DATABASE ${EDU_PLATFORM_DB} TO ${PLATFORM_ADMIN_USER};
GRANT USAGE ON SCHEMA raw TO student_readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA raw TO student_readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE ${EDU_WRITER_USER} IN SCHEMA raw
    GRANT SELECT ON TABLES TO student_readonly;

GRANT ALL PRIVILEGES ON SCHEMA raw TO ${PLATFORM_ADMIN_USER};
GRANT USAGE ON SCHEMA raw TO ${EDU_WRITER_USER};
ALTER DEFAULT PRIVILEGES FOR ROLE ${EDU_WRITER_USER} IN SCHEMA raw
    GRANT ALL ON TABLES TO ${PLATFORM_ADMIN_USER};
SQL
